name: Nightly LC Launcher

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

permissions:
    contents: write

jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      target: windows
                    - os: ubuntu-latest
                      target: linux
                    - os: macos-latest
                      target: darwin
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: latest

            - name: Install installer deps
              shell: bash
              run: |
                if [ "$RUNNER_OS" == "Windows" ]; then
                    choco install nsis
                elif [ "$RUNNER_OS" == "Linux" ]; then
                    wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
                    chmod +x appimagetool
                    sudo mv appimagetool /usr/local/bin/
                elif [ "$RUNNER_OS" == "macOS" ]; then
                    brew install create-dmg
                fi

            - name: Build lib
              run: bun ./build-scripts/build-lib.js ${{ matrix.target }}

            - name: Build app
              run: node ./build-scripts/build.js ${{ matrix.target }}

            - name: Publish release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: nightly-${{ github.run_id }}
                  name: "Nightly Build ${{ github.run_id }}"
                  body: "If you have any issues with the builds below, please contact an LC Launcher dev in our discord!"
                  target_commitish: ${{ github.sha }}
                  generate_release_notes: true
                  prerelease: true
                  allowUpdates: true
                  files: |
                      dist/*.tar.gz
                      dist/*.zip
                      dist/*.exe
                      dist/*.AppImage
                      dist/*.dmg
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
