name: Release LC Launcher
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "BUMP"

permissions:
    contents: write

jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      target: windows
                    - os: ubuntu-latest
                      target: linux
                    - os: ubuntu-24.04-arm
                      target: linux-arm64
                    - os: macos-latest
                      target: darwin
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: latest

            - name: Install installer deps (Windows)
              if: matrix.os == 'windows-latest'
              shell: powershell
              run: choco install nsis -y

            - name: Install installer deps (Mac)
              if: matrix.os == 'macos-latest'
              run: HOMEBREW_REQUIRE_TAP_TRUST=1 brew install create-dmg

            - name: Install installer deps (Linux)
              if: matrix.os == 'ubuntu-latest'
              run: |
                sudo apt-get update
                sudo apt-get install -y zenity libfuse2 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-gl

                wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O linuxdeploy
                chmod +x linuxdeploy
                sudo mv linuxdeploy /usr/local/bin/

                wget https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gstreamer/master/linuxdeploy-plugin-gstreamer.sh -O linuxdeploy-plugin-gstreamer.sh
                chmod +x linuxdeploy-plugin-gstreamer.sh
                sudo mv linuxdeploy-plugin-gstreamer.sh /usr/local/bin/
            
            - name: Install installer deps (Linux ARM64)
              if: matrix.target == 'linux-arm64'
              run: |
                sudo apt-get update
                sudo apt-get install -y zenity libfuse2 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-gl

                wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage -O linuxdeploy
                chmod +x linuxdeploy
                sudo mv linuxdeploy /usr/local/bin/

                wget https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gstreamer/master/linuxdeploy-plugin-gstreamer.sh -O linuxdeploy-plugin-gstreamer.sh
                chmod +x linuxdeploy-plugin-gstreamer.sh
                sudo mv linuxdeploy-plugin-gstreamer.sh /usr/local/bin/

            - name: Build lib
              run: bun ./build-scripts/build-lib.js ${{ matrix.target }}

            - name: Build app
              run: node ./build-scripts/build.js ${{ matrix.target }}

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build-${{ matrix.target }}
                path: |
                  dist/
                  !dist/__*

    build-appimage:
      name: "${{ matrix.name }} (${{ matrix.arch }})"
      runs-on: ${{ matrix.runs-on }}
      strategy:
        matrix:
          include:
            - runs-on: ubuntu-latest
              name: Build AppImage
              arch: x86_64
            - runs-on: ubuntu-24.04-arm
              name: Build AppImage
              arch: aarch64
      container: ghcr.io/pkgforge-dev/archlinux:latest
      steps:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: Preparing Container
          uses: pkgforge-dev/anylinux-setup-action@0964f2258d6c93d1391359978dde081fd8b3c6af # v2
        - name: Install Dependencies
          run: /bin/sh ./build-scripts/sharun/get-dependencies.sh
        - name: Make AppImage
          run: /bin/sh ./build-scripts/sharun/make-appimage.sh
        - name: Upload artifact
          uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
          with:
            name: AppImage-${{ matrix.arch }}
            path: |
              dist/*.AppImage*

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get release details
              id: release_details
              run: |
                VERSION="$(tr -d '\r\n' < BUMP)"
                echo "version=$VERSION" >> "$GITHUB_OUTPUT"
                
                {
                  echo "description<<EOF"
                  cat NOTES.md
                  echo "EOF"
                } >> "$GITHUB_OUTPUT"

            - name: Download artifacts
              uses: actions/download-artifact@v8
              with:
                path: artifacts
                merge-multiple: true

            - name: Publish release
              uses: softprops/action-gh-release@v3
              with:
                tag_name: v${{ steps.release_details.outputs.version }}
                name: "v${{ steps.release_details.outputs.version }}"
                body: ${{ steps.release_details.outputs.description }}
                target_commitish: ${{ github.sha }}
                generate_release_notes: false
                prerelease: false
                make_latest: true
                files: artifacts/*
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}