name: Release LC Launcher
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
on:
    workflow_dispatch: {}
    push:
        branches:
            - main
        paths:
            - "BUMP"

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: Build AppImage
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            name: Build AppImage
            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Preparing Container
        uses: pkgforge-dev/anylinux-setup-action@0964f2258d6c93d1391359978dde081fd8b3c6af # v2
      - name: Install Dependencies
        run: /bin/sh ./build-scripts/sharun/get-dependencies.sh
      - name: Make AppImage
        run: /bin/sh ./build-scripts/sharun/make-appimage.sh
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: AppImage-${{ matrix.arch }}
          path: dist

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release details
        id: release_details
        run: |
          VERSION="$(tr -d '\r\n' < BUMP)"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          
          {
            echo "description<<EOF"
            cat NOTES.md
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: AppImage-*
          path: artifacts
          merge-multiple: true

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.release_details.outputs.version }}
          name: "v${{ steps.release_details.outputs.version }}"
          body: ${{ steps.release_details.outputs.description }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: false
          prerelease: false
          make_latest: true
          files: artifacts/*.AppImage*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}