name: Test build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: windows
          - os: ubuntu-latest
            target: linux
          - os: macos-latest
            target: darwin
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build lib
        run: |
          node ./build-scripts/build-lib.js ${{ matrix.target }}
          
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-${{ github.run_id }}
          target_commitish: ${{ github.sha }}
          name: Dev Build ${{ github.run_id }}
          generate_release_notes: true
          files: |
            dist/**/*.exe
            **/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}